### ISSUE TITLE
GitTools-Action verwenden

### ISSUE THREAD

**Issue by kurmann** [kurmann/GitHub.Workflows#16]

**Comment by kurmann** [comment]
Der Workflow funktioniert immer noch nicht.

Darf ich kurz nachfragen. Es gibt neu "GitTools" und hier ist offensichtlich GitVersion dabei.

https://github.com/marketplace/actions/gittools

---

Wenn du Probleme mit der manuellen Installation und Konfiguration von GitVersion als .NET Global Tool hast und stattdessen eine einfachere Lösung wünschst, kannst du die GitTools Action aus dem GitHub Marketplace verwenden. Diese Action kapselt die Funktionalität von GitVersion und anderen Tools, was den Einrichtungsprozess deutlich vereinfacht.

### Anpassung des Workflows mit GitTools Action

Hier ist, wie du den Workflow anpassen kannst, um die GitTools/GitVersion Action zu verwenden, was eine einfachere und zuverlässigere Integration ermöglicht:

```yaml
name: Create Release Draft

on:
  push:
    branches:
      - main  # Führt diesen Workflow aus, wenn Änderungen an den main Branch gepusht werden

jobs:
  build-and-release:
    runs-on: ubuntu-latest  # Definiert den Runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Holt die gesamte Git-Historie für GitVersion

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9
      with:
        useConfigFile: true
        configFilePath: 'GitVersion.yml'

    - name: Create GitHub Release Draft
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Nutzt das GitHub Token für Authentifizierung
      with:
        tag_name: ${{ steps.gitversion.outputs.semVer }}  # Setzt den Tag-Namen zur Version
        release_name: Release ${{ steps.gitversion.outputs.semVer }}
        draft: true
        body: |
          Changes in this Release:
          - ${{ steps.gitversion.outputs.commitsSinceVersionSource }} commits since last version.
          ### Features
          * New features added
          ### Fixes
          * Bugs fixed

    - name: Tag Repository
      run: |
        git tag ${{ steps.gitversion.outputs.semVer }}
        git push origin ${{ steps.gitversion.outputs.semVer }}
```

### Wichtige Änderungen:

1. **GitTools/GitVersion Action verwenden**: Diese Aktion übernimmt das Herunterladen, Installieren und Ausführen von GitVersion, was den Setup-Prozess vereinfacht. Sie kümmert sich auch um die richtige Anwendung der Konfigurationsdatei.

2. **Ausgabevariablen**: Achten darauf, dass die Ausgabevariablen (`steps.gitversion.outputs.semVer` usw.) den tatsächlichen Outputs der GitTools Action entsprechen. Diese Action setzt typischerweise die Version und andere relevante Daten als Ausgabevariablen, die im weiteren Verlauf des Workflows verwendet werden können.

3. **Vereinfachung der Konfiguration**: Durch die Nutzung einer dedizierten Action für GitVersion werden viele der manuellen Schritte, die früher erforderlich waren (wie die Installation und Pfadkonfiguration), unnötig.

Indem du diese Anpassungen vornimmst, solltest du eine stabilere und zuverlässigere Erfahrung mit GitVersion in deinem GitHub Actions Workflow haben, und die Fehler, die zuvor aufgetreten sind, sollten behoben sein.
