### ISSUE TITLE
Automatische Versionserhöhung nach erfolgreichen Pull-Request auf den Hauptzweig

### ISSUE THREAD

**Issue by kurmann** [kurmann/GitHub.Workflows#21]
Vorabdiskussion:

- #11 

Mögliche GitHub-Action:

- https://github.com/marketplace/actions/net-project-version-updater

**Comment by kurmann** [comment]
Das einzige was ich noch teilweise automatisieren würde, ist das Zusammenfassen von mehreren Features in einen Release? Wie könnte mir Release Drafter helfen wenn mehrere Features ihre eigenen Changelog-Einträge haben.

---

Der Release Drafter kann mit mehreren Pull Requests und deren Changelog-Einträgen umgehen, indem er automatisch alle Änderungen, die seit dem letzten Release in den Hauptbranch (typischerweise `main` oder `master`) gemergt wurden, in einen Release-Entwurf aufnimmt. Jeder Pull Request, der in den Hauptbranch gemergt wird und das passende Label hat, wird von Release Drafter entsprechend berücksichtigt.

Wenn Sie möchten, dass Release Drafter die Änderungen aus mehreren Features zusammenfasst, könnten Sie folgendermaßen vorgehen:

1. **Labeln Sie jeden Pull Request**: Weisen Sie jedem Feature-Pull Request ein Label zu, wie zum Beispiel `feature`. Sie können im Release Drafter für jedes Label eine eigene Kategorie definieren.

2. **Konfiguration des Release Drafters**: In der Konfigurationsdatei des Release Drafters definieren Sie, wie die Einträge für die verschiedenen Labels im Changelog erscheinen sollen. Hier ein Beispiel, wie die Konfiguration aussehen könnte:

```yaml
categories:
  - title: 'Features'
    labels:
      - 'feature'
```

3. **Release-Draft erstellen**: Sobald ein Pull Request mit dem Label `feature` in den Hauptbranch gemergt wird, fügt Release Drafter automatisch den Titel (und optional die Beschreibung) des Pull Requests unter der Kategorie `Features` in den Entwurf des nächsten Releases ein.

4. **Manuelle Überprüfung und Bearbeitung**: Bevor Sie den Release veröffentlichen, können Sie den Entwurf überprüfen und manuell bearbeiten. So können Sie sicherstellen, dass alles korrekt ist und notfalls Änderungen vornehmen.

5. **Release veröffentlichen**: Wenn Sie bereit sind, veröffentlichen Sie den Entwurf als Release. Release Drafter erstellt basierend auf dem Entwurf die finalen Release Notes.

Wenn Sie mehrere Features haben, die über mehrere Pull Requests verteilt sind, sammelt Release Drafter einfach alle entsprechenden Einträge unter der Kategorie `Features` im Changelog des Release-Entwurfs. Sie müssen dann nur noch den Release-Entwurf überprüfen und veröffentlichen, was Ihnen hilft, den Prozess zu vereinfachen und etwas Zeit zu sparen.

**Comment by kurmann** [comment]
Könntest du bitte einen reusable Workflow machen der sich nur im die Versionserhöhung im csproj kümmert. 

Er soll als Eingabeparameter eine Option als Major, Minor, Patch und Preview haben. 

Beim Preview wird die Versionsnummer mit einem „-preview“-Suffix versehen und laufend erhöht

---

Um einen wiederverwendbaren GitHub-Workflow zu erstellen, der sich um die Versionserhöhung in `.csproj`-Dateien kümmert, können Sie die folgenden Schritte ausführen. Hier ist ein Beispiel-Workflow, den Sie als wiederverwendbare Workflow-Datei in Ihrem Repository unter `.github/workflows` speichern können. Der Workflow erhält Eingabeparameter für die Versionstypen `Major`, `Minor`, `Patch` und `Preview`.

### Schritte zur Erstellung eines wiederverwendbaren Workflows:

1. **Erstellen Sie eine YAML-Datei für den wiederverwendbaren Workflow:**

```yaml
name: Bump csproj Version

on:
  workflow_call:
    inputs:
      versionType:
        type: string
        description: 'Type of version increment: Major, Minor, Patch, or Preview'
        required: true
      csprojPath:
        type: string
        description: 'Path to the csproj file to update'
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump Version
        uses: zwaldowski/csproj-version@v1
        with:
          path: ${{ inputs.csprojPath }}
          increment: ${{ inputs.versionType }}
          suffix: ${{ endsWith(inputs.versionType, 'Preview') && 'preview' || '' }}

      - name: Commit and Push Version Bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ inputs.csprojPath }}
          git commit -m "Bump ${inputs.versionType} version: Update csproj"
          git push
```

### Erklärungen:

- **Inputs:** Dieser Workflow nimmt zwei Eingaben: `versionType` und `csprojPath`. `versionType` kann `Major`, `Minor`, `Patch` oder `Preview` sein, und `csprojPath` gibt den Pfad zur `.csproj`-Datei an.
  
- **`on.workflow_call`:** Dies ermöglicht es anderen Workflows, diesen Workflow als wiederverwendbaren Teil aufzurufen.

- **Bump Version:** Dieser Schritt verwendet eine angepasste Version der `csproj-version` Action (hier hypothetisch angenommen, dass sie so verwendet werden kann). Sie müssen möglicherweise eine eigene oder angepasste Aktion verwenden oder schreiben, um genau diese Logik zu implementieren.

- **Commit and Push:** Nachdem die Version erhöht wurde, werden die Änderungen committed und zurück in das Repository gepusht.

### Nutzung des wiederverwendbaren Workflows:

Um diesen wiederverwendbaren Workflow in einem anderen Workflow zu verwenden, könnten Sie folgenden Code verwenden:

```yaml
name: Update Project Version

on:
  push:
    branches:
      - main

jobs:
  bump-version-job:
    uses: ./.github/workflows/bump-csproj-version.yml
    with:
      versionType: 'Minor'
      csprojPath: 'path/to/your/project/file.csproj'
```

Stellen Sie sicher, dass Sie die `zwaldowski/csproj-version`-Action entsprechend Ihren Anforderungen anpassen oder eine eigene Action entwickeln, die die spezifischen Bedingungen für `Major`, `Minor`, `Patch` und `Preview` handhabt. Der obige Code nimmt an, dass solche Anpassungen möglich sind, was jedoch ggf. nicht der Fall ist, ohne dass entsprechende Entwicklungsarbeit an der Action selbst durchgeführt wird.
