### ISSUE TITLE
Unterstützung für Vorschaufassungen

### ISSUE THREAD

**Issue by kurmann** [kurmann/GitHub.Workflows#22]

**Comment by kurmann** [comment]
Nein das scheint zu komplex zu sein. 

Wie funktioniert auf GitHub ein Preview-Release? Versionsnummer?

---

Ein Preview-Release auf GitHub kann mit einer speziell gekennzeichneten Versionsnummer erstellt werden, um deutlich zu machen, dass es sich um eine Vorabversion handelt. Diese Vorabversionen sind nützlich für die Phase vor der endgültigen Freigabe, um Feedback zu sammeln oder um sicherzustellen, dass keine kritischen Fehler in der Software vorhanden sind. Hier sind die Schlüsselschritte und Informationen, um ein effektives Preview-Release auf GitHub zu managen:

### Versionsnummer für Preview-Releases

Die Versionsnummern für Preview-Releases folgen in der Regel dem Semantic Versioning (SemVer) mit zusätzlichen Suffixen wie `-alpha`, `-beta`, `-preview`, oder einem spezifischen Build-Nummer-Suffix. Hier sind einige Beispiele:

- `1.0.0-alpha`
- `1.0.0-beta.1`
- `1.0.0-preview.1`

Diese Suffixe können weiter inkrementiert werden, um aufeinanderfolgende Iterationen zu kennzeichnen, z.B. `1.0.0-preview.2`, `1.0.0-preview.3` usw.

### Erstellung eines Preview-Releases auf GitHub

1. **Tagging**: Erstellen Sie ein Git-Tag mit der Preview-Versionsnummer, z.B. `git tag 1.0.0-preview.1` und pushen Sie dieses Tag zu Ihrem GitHub-Repository: `git push origin 1.0.0-preview.1`.

2. **GitHub Release erstellen**:
   - Navigieren Sie zu Ihrem GitHub-Repository.
   - Gehen Sie zum Abschnitt "Releases".
   - Klicken Sie auf "Draft a new release" oder "Neues Release erstellen".
   - Wählen Sie das Tag aus, das Sie gerade gepusht haben.
   - Geben Sie dem Release einen Titel, der das Preview-Label klar hervorhebt, z.B. "Preview Release 1.0.0-preview.1".
   - Beschreiben Sie die Änderungen oder die wichtigsten Punkte, die Tester wissen sollten.
   - Markieren Sie das Kästchen "This is a pre-release", um deutlich zu machen, dass es sich um ein nicht endgültiges Release handelt.
   - Veröffentlichen Sie das Release.

### Automatisierung der Release-Erstellung

Wenn Sie diesen Prozess automatisieren möchten, können Sie GitHub Actions verwenden, um bei jedem neuen Tag, der einem bestimmten Muster entspricht (z.B. `*-preview.*`), automatisch ein GitHub Release zu erstellen. Hierfür könnten Sie die [actions/create-release](https://github.com/actions/create-release) GitHub Action verwenden, die die Erstellung von Releases automatisiert.

### Beispiel GitHub Action für automatische Preview-Releases

Hier ist ein einfaches Beispiel für eine GitHub Action, die automatisch ein Preview-Release erstellt:

```yaml
name: Create Preview Release

on:
  push:
    tags:
      - '*-preview.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
          body: 'This is a preview release for testing.'
```

### Zusammenfassung

Preview-Releases sind eine effektive Methode, um Software vor der endgültigen Freigabe zu testen. Die Verwendung von Semantic Versioning mit spezifischen Suffixen hilft dabei, die Erwartungen an die Stabilität und Vollständigkeit der Software zu setzen. Durch die Automatisierung des Release-Prozesses können Sie sicherstellen, dass neue Preview-Versionen effizient und konsistent bereitgestellt werden.
