### ISSUE TITLE
Conventional Commits bei Release Drafter nutzen

### ISSUE THREAD

**Issue by kurmann** [kurmann/GitHub.Workflows#23]
Ausgansdiskussion:

- #21

**Comment by kurmann** [comment]
Eine Frage noch. Gibt es eine andere Möglichkeit, dass der Release Drafter Informationen während der Entwicklungszeit sammeln kann um zu verhindern, dass ich bei jeder PullRequest mir die Features nachträglich notieren muss?

---

Ja, der Release Drafter bietet einige Möglichkeiten, Informationen während der Entwicklungszeit zu sammeln und automatisch in die Release Notes zu integrieren, was den Prozess der Dokumentation der Änderungen erleichtert. Hier sind einige Strategien, wie Sie den Release Drafter effektiver nutzen können, um Informationen zu sammeln und Ihre Pull Requests zu organisieren:

### 1. Automatische Kategorisierung durch Labels
Release Drafter kann automatisch Änderungen in den Release Notes kategorisieren, basierend auf den Labels, die Sie Ihren Pull Requests zuweisen. Sie können den Release Drafter so konfigurieren, dass er spezifische Labels wie `feature`, `bug`, `enhancement` usw. erkennt und diese Informationen entsprechend in den Release Notes gruppiert.

#### Beispiel für Release Drafter Konfiguration:
```yaml
categories:
  - title: 'Features'
    labels:
      - 'feature'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Improvements'
    labels:
      - 'enhancement'
```

### 2. Pull Request Titel und Beschreibung
Stellen Sie sicher, dass die Titel und Beschreibungen Ihrer Pull Requests klar und deskriptiv sind. Release Drafter verwendet diese Informationen, um die Einträge in den Release Notes zu erstellen. Ein klar formulierter Titel und eine präzise Beschreibung helfen dabei, die Release Notes verständlich und informativ zu gestalten.

### 3. Automatisches Befüllen von Release Notes
Sie können den Release Drafter so konfigurieren, dass er automatisch eine Zusammenfassung der Änderungen aus dem Inhalt des Pull Requests generiert. Dazu können Sie die `change-template` Option in der Konfigurationsdatei verwenden, um anzupassen, wie die Änderungen formatiert werden.

#### Beispiel für das `change-template`:
```yaml
change-template: '- $TITLE @$AUTHOR (#$NUMBER) - $LABELS'
```

### 4. Verwenden von Draft Pull Requests
Nutzen Sie Draft Pull Requests während der Entwicklungsphase, um Änderungen zu sammeln und zu diskutieren, bevor sie finalisiert werden. Draft Pull Requests werden von Release Drafter nicht erfasst, bis sie als "Ready for review" markiert werden, was Ihnen erlaubt, Änderungen zu bündeln und zu organisieren, bevor sie in den Release Notes erscheinen.

### 5. Automatisches Tracking von Issues
Wenn Ihre Pull Requests Issues schließen oder mit ihnen verknüpft sind, stellen Sie sicher, dass Sie dies in der Pull Request-Beschreibung erwähnen (z.B. durch "Fixes #123"). Release Drafter kann diese Informationen nutzen, um relevante Issues in den Release Notes zu verlinken, was zusätzlichen Kontext bietet.

### 6. Verwendung einer Konvention für Commit-Nachrichten
Obwohl Release Drafter hauptsächlich auf Pull Requests basiert, kann eine Konvention für Commit-Nachrichten, wie Conventional Commits, dazu beitragen, die Konsistenz und Klarheit der Informationen zu erhöhen, die in die Pull Requests und damit in die Release Notes einfließen.

Durch die Anwendung dieser Methoden kann Release Drafter effektiv dazu beitragen, während der Entwicklungszeit Informationen zu sammeln, ohne dass Sie manuell Notizen zu jedem Pull Request machen müssen. Dies spart Zeit und stellt sicher, dass die Release Notes vollständig und genau sind.

**Comment by kurmann** [comment]
Wie verwende ich Conventional Commits für Release Drafter? Ich habe diese Möglichkeit bisher nur bei GitVersion oder semantic-versioning testen wollen.

---

Die Verwendung von Conventional Commits in Kombination mit Release Drafter kann den Prozess der Erstellung automatisierter und informativer Release Notes deutlich verbessern. Conventional Commits bieten eine standardisierte Methode, Commit-Nachrichten zu strukturieren, was wiederum das automatische Generieren von Release Notes durch Tools wie Release Drafter vereinfacht.

### Integration von Conventional Commits mit Release Drafter

Release Drafter selbst verarbeitet keine Commit-Nachrichten direkt zur Versionserzeugung, wie es Semantic Release oder GitVersion tun, aber Sie können die Struktur von Conventional Commits nutzen, um Ihre Release Notes besser zu organisieren und zu kategorisieren. Hier ist, wie Sie dies umsetzen können:

1. **Commit-Nachrichten konsequent formatieren:**
   Verwenden Sie das Conventional Commits Format für alle Ihre Commits. Typische Conventional Commits beginnen mit einem Präfix, das den Typ der Änderung anzeigt (`feat`, `fix`, `chore`, `docs`, `style`, `refactor`, `perf`, `test`), gefolgt von einem optionalen Scope und einer Beschreibung. Zum Beispiel:
   ```
   feat(auth): add oauth token authentication
   fix(server): resolve memory leak
   ```

2. **Pull Requests entsprechend benennen:**
   Wenn Sie einen Pull Request erstellen, verwenden Sie einen Titel, der die wesentlichen Änderungen zusammenfasst und idealerweise auch das Conventional Commit Format widerspiegelt. Dies erleichtert es Release Drafter, die Informationen korrekt zu erfassen und in die Release Notes zu integrieren.

3. **Konfiguration von Release Drafter:**
   Passen Sie die Konfiguration von Release Drafter so an, dass sie das Conventional Commits Schema nutzt. Sie können zum Beispiel verschiedene Kategorien für Features (`feat`), Bug Fixes (`fix`) und andere Typen definieren. In Ihrer `.github/release-drafter.yml` könnten Sie Folgendes angeben:

   ```yaml
   categories:
     - title: 'Features'
       labels:
         - 'feature'
         - 'feat'
     - title: 'Bug Fixes'
       labels:
         - 'fix'
     - title: 'Documentation'
       labels:
         - 'docs'

   change-template: '- $TITLE (@$AUTHOR) #@$NUMBER'
   ```

4. **Automatische Label-Zuweisung in Pull Requests:**
   Um den Prozess weiter zu automatisieren, können Sie GitHub Actions verwenden, um automatisch Labels zu Pull Requests hinzuzufügen, basierend auf den in den Commits verwendeten Conventional Commits-Typen. Zum Beispiel könnte eine Action Commits in einem Pull Request scannen und entsprechende Labels wie `feat` oder `fix` zuweisen.

5. **Review und Feinabstimmung:**
   Bevor Sie einen Release finalisieren, überprüfen Sie den von Release Drafter erstellten Entwurf der Release Notes. Anpassungen können manuell vorgenommen werden, um sicherzustellen, dass die Informationen präzise und nützlich sind.

### Beispiel für eine GitHub Action zur Label-Zuweisung

Hier ist ein einfaches Beispiel für eine GitHub Action, die prüfen könnte, welche Arten von Conventional Commits in einem Pull Request vorhanden sind, und entsprechende Labels anwendet:

```yaml
name: Label PRs
on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Apply labels based on commit types
        uses: some-github-action-that-applies-labels-based-on-commit-messages # Hypothetische Action
```

Dies ist ein konzeptueller Überblick darüber, wie Sie Conventional Commits in Verbindung mit Release Drafter verwenden können, um den Prozess der Release-Dokumentation zu automatisieren. Bitte beachten Sie, dass Sie möglicherweise spezifische Tools oder Skripte benötigen oder schreiben müssen, um die vollständige Automatisierung zu erreichen.
