### ISSUE TITLE
Nächsthöhere Version vorschlagen

### ISSUE THREAD

**Issue by kurmann** [kurmann/GitHub.Workflows#30]
Neue Funktion: Versionsvergabe über den Release Crafter lösen.

Vorab-Aufgabe: 
- #31 

Aktuell nicht in Ordnung:
![image](https://github.com/kurmann/GitHub.Workflows/assets/2642655/36c618ca-7a25-4698-84d2-987f12dd076d)

**Comment by kurmann** [comment]
````yaml

name: Reusable workflow

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "firstword=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "secondword=world" >> $GITHUB_OUTPUT

```

**Comment by kurmann** [comment]
```yaml
name: Call a reusable workflow and use its outputs

on:
  workflow_dispatch:

jobs:
  job1:
    uses: octo-org/example-repo/.github/workflows/called-workflow.yml@v1

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
```
