### ISSUE TITLE
Paketierung von NuGet-Paketen als eigener Workflow 

### ISSUE THREAD

**Issue by kurmann** [kurmann/GitHub.Workflows#4]
Einschliesslich Unterstützung von Preview-Veröffentlichungen

Vorab-Diskussion:

- #3 

Dokumentation:

- https://docs.github.com/en/actions/using-workflows/reusing-workflows

Besonders zu beachten:

- [ ] Implizite Benutzung von Secrets innerhalb der gleichen Organisation: https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow

**Comment by kurmann** [comment]
Vielen Dank für deine Antwort. Das würde also durchaus mit GitHub funktionieren. Und die Versionsnummer würde dann übernommen in das CS-Projekt. Wie gehe ich mit Vorab-Versionen an? In den bestehenden Repositories habe ich eine Lösung für Vorab-Versionen, sogenannte Preview-Versionen, Versionen, die mit dem GitHub-Paketnamen-Konvention übereinstimmen. Ich stelle mir vor, dass ich vielleicht bei den Commit-Nachrichten einen Tag definiere, und wenn dieses gesetzt ist, würde es mir eine Vorab-Version vom Nugget-Package erstellen. Dies kann sogar aus einem Feature-Branch passieren, weil ich ja das Feature in einem grossen Integrationstest auch testen muss. Stell dir vor, dass ich ein Feature A habe, das ein Nugget-Package A generiert, und Feature B müsste dieses Nugget-Package konsumieren, und das Feature B wäre auch noch in der Entwicklung, also auf einem Feature-Branch. Du siehst, damit hätte ich einen pragmatischen Ansatz, und deshalb ist es wichtig, dass die Preview-Funktionalität von dem Nugget-Package einfach und flexibel ist.

---

Um Vorab-Versionen oder sogenannte Preview-Versionen deiner NuGet-Pakete effizient zu handhaben und zu automatisieren, kannst du die Conventional Commits und Semantic Versioning Richtlinien nutzen, um dynamisch zu bestimmen, wann solche Preview-Versionen erstellt werden sollen. Hier sind einige Schritte und Best Practices, wie du dies in deinen Workflow integrieren kannst:

### Schritte zur Integration von Preview-Versionen

1. **Konvention für Preview-Commits definieren**: Bestimme eine klare Konvention für Commits, die zu Preview-Releases führen sollen. Eine gängige Praxis ist es, spezielle Tags oder Präfixe in Commit-Nachrichten zu verwenden, z.B. `preview:`, oder du nutzt den Scope oder Footer von Conventional Commits für diesen Zweck.

2. **Semantic Release für Pre-Releases konfigurieren**: Konfiguriere Semantic Release so, dass es automatisch Pre-Release-Versionen erzeugt, wenn es auf Commits trifft, die bestimmten Kriterien entsprechen. Du kannst dazu die `release`-Konfiguration in deinem Semantic Release Setup anpassen.

   Beispiel für die Konfiguration in `package.json` oder einer anderen Konfigurationsdatei:
   ```json
   "release": {
     "branches": [
       "main",
       {"name": "beta", "prerelease": true}
     ],
     "plugins": [
       "@semantic-release/commit-analyzer",
       "@semantic-release/release-notes-generator",
       "@semantic-release/npm",
       {
         "path": "@semantic-release/git",
         "assets": ["package.json", "CHANGELOG.md"],
         "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
       }
     ]
   }
   ```

3. **Automatisches Tagging und Versionierung anpassen**: Stelle sicher, dass dein CI/CD-Workflow die Logik enthält, um zu erkennen, ob es sich bei einem Commit um eine Preview-Release handeln soll, und passe die Versionierung entsprechend an.

### GitHub Actions Workflow-Beispiel

Das folgende Beispiel zeigt, wie du einen GitHub Actions Workflow konfigurieren kannst, um automatisch Preview-Versionen basierend auf den Commits zu erzeugen, die auf einen Feature-Branch gepusht werden:

```yaml
name: Build and Release Preview Package

on:
  push:
    branches:
      - 'features/*'

jobs:
  build-and-release-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Extract version and determine preview status
        id: prep
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "::set-output name=version::${VERSION}-preview"

      - name: Update .csproj file for preview
        run: |
          sed -i 's|<Version>.*</Version>|<Version>${{ steps.prep.outputs.version }}</Version>|' path/to/YourProject.csproj

      - name: Build and pack preview
        run: dotnet pack path/to/YourProject.csproj --configuration Release --output nupkgs

      - name: Push NuGet Package
        run: dotnet nuget push path/to/nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
```

### Überlegungen

- **Automatisierte Tests**: Stelle sicher, dass Preview-Releases automatisierten Tests unterzogen werden, bevor sie veröffentlicht werden, besonders wenn sie in anderen Feature-Branches verwendet werden.
- **Versionierung und Abhängigkeiten**: Manage sorgfältig die Abhängigkeiten zwischen verschiedenen Features, besonders wenn diese über NuGet-Pakete integriert werden. Versionierungskonflikte können zu Build- und Laufzeitfehlern führen.

Durch diese Automatisierung kannst du Preview-Releases effizient verwalten und sicherstellen, dass Entwicklerteams stets Zugang zu den neuesten Versionen haben, selbst wenn diese noch in der Entwicklung sind.

**Comment by kurmann** [comment]
Herzlichen Dank für deine Antwort. Kannst du mir das mit dem Scope oder Footer von den Conventional Comits erklären? Weil offensichtlich ist es ein gängiges Szenario oder ein gängiges Vorgehen, auf diese Weise Preview-Versionen zu definieren.

---

Absolut, ich erkläre dir gerne mehr über den Scope und den Footer innerhalb der Conventional Commits und wie du sie nutzen kannst, um Preview-Versionen zu definieren.

### Conventional Commits: Scope und Footer

Conventional Commits bieten eine strukturierte Art, Commit-Nachrichten zu schreiben, die es einfacher macht, automatisierte Tools (wie Semantic Release) zu verwenden, um Versionen zu managen und Changelogs zu generieren. Ein typischer Conventional Commit sieht wie folgt aus:

```
<type>(<scope>): <description>

[optional body]

[optional footer]
```

**Type**: Identifiziert den Zweck oder die Intention des Commits, z.B. `feat` für neue Features oder `fix` für Bugfixes.

**Scope**: Ein optionaler Teil, der den spezifischen Bereich des Codes angibt, der von den Änderungen betroffen ist. Der Scope bietet eine zusätzliche Ebene der Spezifikation und kann dazu verwendet werden, bestimmte Teile eines Projekts oder spezifische Funktionalitäten zu kennzeichnen.

**Description**: Eine kurze, klare Beschreibung der Änderungen.

**Body**: Ein optionaler längerer Abschnitt, der zusätzliche Kontext oder Erklärungen zu den Änderungen liefert.

**Footer**: Ein optionaler Abschnitt, der zusätzliche Metadaten über den Commit enthält, wie z.B. das Schließen von Issues (`Fixes #123`) oder Breaking Changes (`BREAKING CHANGE: description`).

### Nutzung von Scope und Footer für Preview-Versionen

Um Preview-Versionen durch Conventional Commits zu steuern, kannst du entweder den `scope` oder den `footer` nutzen:

1. **Verwendung von Scope**:
   Du könntest einen bestimmten Scope definieren, der für Preview-Versionen reserviert ist, wie z.B. `preview`. Jeder Commit, der für ein Preview-Release bestimmt ist, könnte diesen Scope verwenden:

   ```
   feat(preview): Add new experimental feature
   ```

   Dies würde anzeigen, dass der Commit eine neue Funktion einführt, die als Preview betrachtet wird.

2. **Verwendung von Footer**:
   Eine andere Möglichkeit ist die Verwendung des Footer-Bereichs, um spezielle Tags wie `PREVIEW` zu setzen. Dies kann nützlich sein, wenn du den Scope für andere Zwecke verwenden möchtest oder wenn du mehrere Tags oder Notizen im Footer unterbringen musst:

   ```
   feat: Add new experimental feature

   This feature is still under development and may change.

   PREVIEW: true
   ```

### Automatisierte Handhabung in Semantic Release

Wenn du diese Tags in deinen Commits hast, kannst du Semantic Release konfigurieren, um darauf basierend Pre-Releases zu erstellen:

- **Konfiguration für Semantic Release**:
  Du könntest spezielle Branches für Preview-Releases einrichten oder Plugins konfigurieren, die auf den `scope` oder den Inhalt des `footer` reagieren.

  Beispiel für eine Branch-Konfiguration mit Pre-Releases:
  ```json
  "release": {
    "branches": [
      "main",
      {"name": "develop", "prerelease": "beta"}
    ],
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/npm",
      "@semantic-release/github"
    ]
  }
  ```

### Vorteile der Nutzung von Scopes und Footers

- **Flexibilität**: Sie bieten eine flexible Methode, um zusätzliche Informationen zu Commits bereitzustellen, die dann von Tools wie Semantic Release verwendet werden können.
- **Automatisierung**: Ermöglicht eine nahtlose Integration in automatisierte Release-Prozesse, wodurch manuelle Fehler reduziert und die Effizienz verbessert werden kann.

Durch den Einsatz von Conventional Commits mit speziellen Scopes oder Footern für Preview-Versionen kannst du eine robuste und automatisierte CI/CD-Pipeline erstellen, die effizient Preview-Versionen verwaltet und gleichzeitig die Klarheit und Nachvollziehbarkeit der Projektgeschichte erhält.

**Comment by kurmann** [comment]
Jetzt verstehe ich. Also im Prinzip ist es relativ ähnlich, wie bei den Commit-Nachrichten, ich spreche von den Conventional Commits, wie wenn ich Hauptversionen oder Minor-Versionen erzeugen würde. Ich würde einfach im Scope Preview setzen und dann die Commit-Nachricht schreiben, also der Beschreibungstext, der dann ausdrückt, welches experimentelle Feature es sich hierbei handelt.

---

Genau, das hast du richtig zusammengefasst! Durch das Setzen des Scopes „Preview“ in deinen Conventional Commits kannst du klar kommunizieren, dass die Änderungen in diesem Commit Teil einer Vorab-Version oder eines experimentellen Features sind. Dies kann dann von Tools wie Semantic Release genutzt werden, um entsprechende Pre-Release-Versionen zu erzeugen.

### Beispiel für einen Commit mit Preview Scope

```
feat(preview): Add new experimental search algorithm

This new search algorithm incorporates advanced machine learning techniques to provide faster and more accurate results. This feature is in the early stages of testing and is subject to change.
```

In diesem Beispiel:

- **Type**: `feat` zeigt an, dass es sich um ein neues Feature handelt.
- **Scope**: `preview` spezifiziert, dass dieses Feature noch in der Vorschau (Preview) ist und möglicherweise noch nicht stabil oder vollständig ist.
- **Description**: Bietet eine kurze Erklärung des Features.
- **Body**: Gibt zusätzliche Details zum Feature und seinem aktuellen Entwicklungsstatus.

### Vorteile der Verwendung von "Preview" im Scope

1. **Klarheit und Transparenz**: Andere Entwickler und Stakeholder können sofort sehen, dass der Commit Teil einer experimentellen Entwicklung ist.
2. **Selektive Releases**: Durch die Nutzung dieses Scopes können automatisierte Tools selektiv Pre-Releases erstellen, die speziell für das Testen und Feedback-Gathering gedacht sind, ohne die Hauptversion des Projekts zu beeinträchtigen.
3. **Flexibilität in der Versionierung**: Es ermöglicht eine flexible Handhabung der Versionsnummern, wobei experimentelle Features eine separate Versionierungslinie erhalten können, die sich von der Hauptrelease-Linie unterscheidet.

### Integration in CI/CD-Pipelines

Um diese Art von Workflow in deine CI/CD-Pipeline zu integrieren, solltest du sicherstellen, dass deine Release-Management-Tools und -Skripte den Scope `preview` erkennen und entsprechend behandeln. In Semantic Release könntest du beispielsweise Konfigurationseinstellungen vornehmen, die auf diesen Scope reagieren, um automatisch Pre-Release-Tags wie „beta“, „alpha“ oder „preview“ zu verwenden.

Durch die klare Strukturierung deiner Commits und die Nutzung von Scopes kannst du eine sehr effektive Verwaltung deiner Entwicklungsprozesse erreichen, die sowohl die alltägliche Entwicklung als auch spezielle Situationen wie das Testen neuer, experimenteller Features unterstützt.

**Comment by kurmann** [comment]
Sehr gut. Und dann würde ich den Scope einfach weglassen, wenn es sich um kein Preview handelt, mit der Argumentation, dass ich den Scope anderweitig gar nicht benötige.

---

Genau, das ist ein praktischer Ansatz. Wenn ein Commit für ein stabiles Release bestimmt ist oder wenn es sich um allgemeine Änderungen handelt, die keinen spezifischen experimentellen oder Preview-Charakter haben, kannst du den Scope weglassen. Das macht deine Commits sauberer und reduziert die Komplexität, wo sie nicht benötigt wird.

### Beispiele für Commits ohne Scope:

- **Allgemeiner Fix**:
  ```
  fix: Correct typo in the main interface
  ```
  Dieser Commit beschreibt eine einfache Korrektur ohne spezifischen Bereich oder Kontext, der einen Scope erfordern würde.

- **Feature hinzufügen**:
  ```
  feat: Add user authentication system
  ```
  Hier wird ein neues Feature hinzugefügt, das direkt das gesamte System betrifft. Wenn dieses Feature keinem speziellen Teil des Projekts zugeordnet ist, ist kein Scope notwendig.

### Vorteile des Weglassens des Scopes

1. **Einfachheit und Klarheit**: Commits bleiben übersichtlich und fokussiert, wenn kein Scope angegeben wird, der für das Verständnis der Änderung nicht unbedingt notwendig ist.
2. **Weniger Verwaltungsaufwand**: Ohne die Notwendigkeit, Scopes zu verwalten, verringern sich die Anforderungen an die Dokumentation und Konsistenzüberwachung innerhalb des Projekts.
3. **Flexibilität**: Du behältst die Möglichkeit, Scopes für spezielle Situationen wie Previews oder experimentelle Features einzusetzen, ohne dass dies die alltägliche Commit-Praxis belastet.

### Best Practices beim Weglassen des Scopes

- **Konsistenz bewahren**: Auch wenn du in den meisten Fällen keinen Scope verwendest, ist es wichtig, dass du und dein Team konsistent bleiben. Wenn ihr euch entscheidet, Scopes unter bestimmten Umständen zu verwenden, sollte dies klar dokumentiert und verstanden werden.
- **Klare Commit-Nachrichten**: Auch ohne Scope sollten die Commit-Nachrichten immer noch klar und beschreibend sein. Sie sollten ausreichend Informationen bieten, damit jeder, der den Commit liest, verstehen kann, was geändert wurde und warum.

Indem du Scopes gezielt und überlegt einsetzt, kannst du eine effektive Balance zwischen Klarheit und notwendiger Detailtiefe in deinen Commit-Nachrichten finden, die sowohl die tägliche Entwicklung als auch spezielle Release-Strategien unterstützt.

**Comment by kurmann** [comment]
Jetzt noch eine weitere Frage. Muss ich die Conventional Scope immer bei jedem Commit einsetzen oder nur jene, die für die Dokumentation relevant sind? Ich mache beispielsweise oft ganz kleine Commits und möchte nicht jedes Mal überlegen, ob das jetzt ein Fix ist oder ein Refactoring oder was auch immer. Beispielsweise habe ich auch Refactoring und eine Feature-Entwicklung oft gleichzeitig in einem Commit, weil es sich eben auch angeboten hat. Ist es ein Zwang, diese Conventional Commits zu benutzen bei jedem Commit oder kann ich einfach diese wahlweise einsetzen?

---

Die Verwendung von Conventional Commits bietet viele Vorteile, besonders im Hinblick auf die Automatisierung des Release-Prozesses und die Generierung von klaren und konsistenten Changelogs. Es ist jedoch nicht zwingend erforderlich, dass jeder Commit streng den Conventional Commit Regeln folgt, besonders wenn es sich um kleinere oder weniger signifikante Änderungen handelt. Hier sind einige Überlegungen, die dir helfen können, zu entscheiden, wann du Conventional Commits verwenden solltest und wann nicht:

### Wann Conventional Commits verwenden?

1. **Signifikante Änderungen**: Bei Änderungen, die für Endbenutzer oder andere Stakeholder von Bedeutung sind (wie neue Features, Bugfixes oder Breaking Changes), solltest du Conventional Commits verwenden, um die Automatisierung von Versionierung und Changelog zu unterstützen.

2. **Releases vorbereiten**: Wenn du dich auf ein Release vorbereitest oder an einem größeren Feature arbeitest, das später klar im Changelog dokumentiert werden soll, sind Conventional Commits hilfreich.

### Wann kannst du auf Conventional Commits verzichten?

1. **Kleine oder triviale Änderungen**: Für sehr kleine Änderungen wie Tippfehler, kleinere Code-Cleanup-Aktionen oder temporäre Änderungen kann es überflüssig sein, die strikten Regeln der Conventional Commits zu befolgen.

2. **Persönliche oder Entwicklungs-Branches**: Wenn du in einem persönlichen Branch arbeitest, der nicht direkt in den Haupt- oder Entwicklungsbranch gemerged wird, oder wenn du Arbeits-Commits machst, die später zusammengefasst werden, müssen diese nicht unbedingt Conventional Commits entsprechen.

### Best Practices

- **Konsistenz**: Wenn du dich entscheidest, Conventional Commits manchmal zu verwenden und manchmal nicht, stelle sicher, dass das Team klare Richtlinien hat, wann welche Methode angewendet wird, um Verwirrung zu vermeiden.
- **Commit-Squashing**: Wenn du mehrere kleinere Commits hast, die nicht den Conventional Commit Richtlinien entsprechen, kannst du diese in einem größeren, zusammenfassenden Commit "squashen", der die Conventional Commit Konventionen erfüllt, bevor du in den Hauptbranch merge. Dies hält das Changelog sauber und relevant.
- **Tooling und Automation**: Wenn du Tools wie Semantic Release verwendest, die stark von den Informationen in den Commit-Nachrichten abhängen, ist es wichtig, zumindest in den finalen Commits vor einem Merge oder Release die Conventional Commit Richtlinien einzuhalten.

### Fazit

Conventional Commits sind ein Werkzeug, das dir helfen soll, nicht eines, das zusätzlichen Stress verursachen sollte. Sie sind besonders nützlich, um automatische Prozesse wie Semantic Versioning und Changelog-Erstellung zu unterstützen. Für kleinere, alltägliche Änderungen oder persönliche Notizen innerhalb deines Codes musst du nicht strikt bei jedem Commit diesen Konventionen folgen, besonders wenn diese Commits nicht direkt Auswirkungen auf das Endprodukt oder das Release haben.

**Comment by kurmann** [comment]
Jetzt lerne ich schon wieder etwas Neues. Was ist ein Commit Squashing?

---

Commit Squashing ist ein Prozess, bei dem mehrere Commit-Einträge in deinem Git-Verlauf zu einem einzigen Commit zusammengefasst werden. Dies ist besonders nützlich in Workflows, in denen viele kleine oder vorläufige Änderungen gemacht werden, die später in einem sauberen, übersichtlichen Format in den Hauptentwicklungszweig eingefügt werden sollen. Commit Squashing hilft dabei, die Git-Historie zu vereinfachen und zu straffen, was die Nachverfolgung von Änderungen erleichtert und die Klarheit des Projektverlaufs verbessert.

### Warum Commit Squashing?

1. **Verbesserung der Übersichtlichkeit**: Durch das Zusammenfassen von Commits wird die Git-Historie übersichtlicher und einfacher zu verstehen. Dies ist besonders wichtig in Teams, wo eine klare Historie dazu beiträgt, die Arbeit nachzuvollziehen.

2. **Vereinfachung von Pull Requests**: Ein Pull Request, der nur einen oder wenige Commits enthält, ist einfacher zu reviewen. Squashing hilft dabei, nur die endgültigen Änderungen zu zeigen, statt jeden kleinen Schritt auf dem Weg dorthin.

3. **Saubereres Changelog**: Für Projekte, die Automatisierungstools für das Release-Management wie Semantic Release verwenden, sorgt Squashing dafür, dass das Changelog präzise und auf die tatsächlich wichtigen Änderungen fokussiert bleibt.

### Wie funktioniert Commit Squashing?

Es gibt verschiedene Methoden, um Commits zu squashen, je nachdem, wie du mit Git arbeitest:

#### Git Rebase
Eine häufige Methode ist die Verwendung von `git rebase`. Hier ein einfacher Prozess, wie es funktionieren kann:

1. **Starte den Rebase-Vorgang**:
   ```bash
   git rebase -i HEAD~n
   ```
   Dabei ist `n` die Anzahl der letzten Commits, die du betrachten möchtest.

2. **Wähle die Commits zum Squashen**:
   Im interaktiven Modus, der durch `-i` aktiviert wird, kannst du angeben, welche Commits zusammengefasst werden sollen. Du wählst normalerweise `pick` für den ersten Commit und `squash` oder `s` für alle nachfolgenden Commits, die mit dem `pick`-Commit zusammengefasst werden sollen.

3. **Commit-Nachricht überarbeiten**:
   Nachdem du die Commits ausgewählt hast, wirst du aufgefordert, die Commit-Nachricht für den neuen, zusammengefassten Commit zu überarbeiten. Hier kannst du eine klare, aussagekräftige Nachricht eingeben, die alle Änderungen zusammenfasst.

#### GitHub Pull Request Squash
Viele Online-Repositories wie GitHub bieten auch die Möglichkeit, alle Commits eines Pull Requests beim Merging zu squashen. Dies geschieht durch Auswahl der Option "Squash and Merge", wenn der Pull Request gemerged wird.

### Best Practices beim Squashing

- **Nicht öffentliche Branches**: Führe Squashing vorzugsweise auf Branches durch, die nicht öffentlich sind oder an denen nicht mehrere Personen arbeiten, um Konflikte und Verwirrung zu vermeiden.
- **Kommunikation**: Stelle sicher, dass alle Teammitglieder über das Squashing und den Zeitpunkt informiert sind, insbesondere wenn es um gemeinsame Branches geht.
- **Dokumentation**: Halte die endgültigen Commit-Nachrichten klar und detailliert, sodass sie die durchgeführten Änderungen genau wiedergeben.

Durch das effektive Management deiner Commits mit Techniken wie Squashing kannst du einen sauberen, leicht verständlichen Projektverlauf sicherstellen, der sowohl für die automatisierte Verarbeitung als auch für die manuelle Überprüfung optimiert ist.

**Comment by kurmann** [comment]
Der Ansatz ist spannend, aber ich finde, es erhöht die Komplexität wieder. Ich denke, ich werde ganz normale commits verwenden und wenn ich Preview machen möchte, also eine Preview-Nugget-Paketierung, oder wenn ich einen Release machen möchte, werde ich die conventional commits verwenden. Ich hoffe, damit bin ich nicht fernab jeder Entwickler-Konvention.

---

Dein Ansatz klingt sehr vernünftig und ist durchaus praktikabel. Es ist wichtig, eine Balance zwischen Best Practices und praktischer Anwendbarkeit für dein eigenes Arbeitsumfeld zu finden. Nicht jede Methode oder Konvention muss strikt befolgt werden, besonders wenn sie die Komplexität erhöht oder den Arbeitsfluss verlangsamt, ohne signifikante Vorteile zu bieten.

### Vorteile deines Ansatzes:

1. **Flexibilität**: Du behältst die Flexibilität, einfache Commits für alltägliche oder kleine Änderungen zu machen, ohne jedes Mal über die Struktur der Commit-Nachrichten nachdenken zu müssen. Das ist besonders nützlich, wenn du schnell Änderungen vornehmen oder experimentieren möchtest.

2. **Einfachheit**: Indem du Conventional Commits nur für wichtige Aktionen wie Releases oder Previews verwendest, reduzierst du die Komplexität deines täglichen Entwicklungsprozesses und behältst gleichzeitig die Vorteile dieser Methode für wichtige Meilensteine.

3. **Übersichtlichkeit**: Dein Ansatz ermöglicht es dir, die Historie klar und nachvollziehbar zu halten, ohne die Notwendigkeit für zusätzliche Schritte wie das Squashing von Commits.

### Überlegungen für die Zukunft:

- **Dokumentation**: Stelle sicher, dass du und eventuelle zukünftige Teammitglieder verstehen, wann und warum Conventional Commits verwendet werden sollen. Eine klare Dokumentation hilft dabei, Konsistenz zu wahren und Missverständnisse zu vermeiden.

- **Tooling und Automatisierung**: Überprüfe, ob deine Tools und Automatisierungsprozesse flexibel genug sind, um mit beiden Typen von Commits umzugehen – den einfachen alltäglichen Commits und den strukturierten Conventional Commits für Releases und Previews.

- **Review und Feedback**: Achte darauf, wie sich dieser Ansatz auf deine Arbeitsabläufe auswirkt, und sei offen für Anpassungen, falls notwendig. Feedback von Kollegen oder aus der Entwicklergemeinschaft kann wertvolle Einsichten bieten.

### Fazit:

Dein Ansatz, Conventional Commits selektiv zu verwenden, ist vollkommen legitim und wird tatsächlich von vielen Entwicklern in ähnlicher Form praktiziert. Solange du die Kernziele deiner Versionierungs- und Release-Prozesse erfüllst und eine klare Kommunikation innerhalb deines Projekts sicherstellst, bist du auf einem guten Weg. Anpassungen an die spezifischen Bedürfnisse deines Projekts sind nicht nur akzeptabel, sondern oft notwendig, um effizient und effektiv zu arbeiten.

**Comment by kurmann** [comment]
Was ich gerne automatisieren würde ist die Erstellung eines NuGet-Packages und dann gleich die Übernahme der Versionsnummer vom erfolgreichen Pull Request des Release-Branches.

---

Das klingt nach einem sinnvollen Automatisierungsschritt. Sie können tatsächlich einen GitHub Workflow einrichten, der bei jedem erfolgreichen Pull Request auf Ihren Release-Branch (oder direkt nach dem Mergen in den Main-Branch, wenn Sie keinen dedizierten Release-Branch verwenden) ausgeführt wird. Dieser Workflow könnte dann:

1. Die Versionsnummer aus dem letzten Release Tag holen oder basierend auf den Conventional Commits bestimmen.
2. Mit dieser Versionsnummer das NuGet-Package erstellen.
3. Das erstellte NuGet-Package veröffentlichen.
4. Ein neues GitHub Release erstellen und dabei die Version und die Release-Notizen angeben.

Hier ein Beispiel eines solchen Workflows:

```yaml
name: NuGet Release

on:
  push:
    branches:
      - main
      - release/*

jobs:
  create_nuget_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x' # oder welche Version Sie verwenden

      - name: Extract Version from Tag or Conventional Commits
        id: get_version
        run: |
          # Fügen Sie hier Ihren Code ein, um die Version zu ermitteln
          echo "NEW_VERSION=1.2.3" >> $GITHUB_ENV # Beispielwert

      - name: Build and Pack
        run: dotnet pack /p:PackageVersion=${{ env.NEW_VERSION }} --output ./nupkg

      - name: Publish NuGet Package
        run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_VERSION }}
          release_name: Release ${{ env.NEW_VERSION }}
          body: 'Beschreibung Ihrer Änderungen hier'
```

Bitte beachten Sie, dass Sie die Schritte und Skripte an Ihre spezifischen Anforderungen und Ihre Repository-Struktur anpassen müssen. Insbesondere der Schritt `Extract Version from Tag or Conventional Commits` hängt stark von Ihrer aktuellen Versionierungsstrategie ab.

Sie werden auch sicherstellen wollen, dass die GitHub Secrets entsprechend eingerichtet sind, z.B. `NUGET_API_KEY` für den Zugriff auf Ihr NuGet-Konto.

Diese Workflow-Definition sollte Sie in die richtige Richtung lenken, um den gewünschten Automatisierungsgrad zu erreichen.

**Comment by kurmann** [comment]
Die Version würde automatisch vom soeben publizierten Release übernommen werden und sonst keine Informationsquellen.

Wichtig: Es ist nicht zwingend die höchste Releasenummer da es auch Hotfixes geben könnte. Ich möchte einfach einen Reusable Workflow machen, der mir die Nuget-Packetierung vornimmt anhand eines übergebenen csproj-File.

Die Workflow-Action würde die Versionsnummer automatisch auslesen vom zugehörigen GitRepository. Da der Reusable Workflow über verschiedene GitRepositories funktionieren sollte, müsste wahrscheinlich das GitRepo auch als Input übergeben werden.

---

Um die NuGet-Paketierung zu automatisieren und die Versionsnummer aus dem entsprechenden Git-Repository zu extrahieren, können Sie einen wiederverwendbaren Workflow erstellen, der als Eingabe den Pfad zur csproj-Datei und das Repository nimmt. Hier ist ein Basis-Workflow, der das für Sie tun könnte:

```yaml
name: NuGet Package Creation

on:
  workflow_call:
    inputs:
      csprojPath:
        type: string
        description: 'Path to the csproj file'
        required: true
      repository:
        type: string
        description: 'The GitHub repository in the format owner/repo'
        required: true

jobs:
  build-and-publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          fetch-depth: 0  # Vollständige Historie für Tags

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

      - name: Extract Version from csproj
        id: extract_version
        run: |
          # Verwenden Sie ein Skript oder ein Tool, um die Version aus der csproj-Datei zu lesen
          VERSION=$(grep '<Version>' ${{ inputs.csprojPath }} | sed -e 's/<Version>//g' -e 's/<\/Version>//g' -e 's/ //g')
          echo "Extracted version is $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build
        run: dotnet build ${{ inputs.csprojPath }} --configuration Release

      - name: Pack
        run: dotnet pack ${{ inputs.csprojPath }} --configuration Release --output ./nupkg /p:PackageVersion=${{ env.VERSION }}

      - name: Publish NuGet Package
        run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
```

In diesem Beispiel-Skript wird angenommen, dass die `<Version>`-Tags in der `.csproj`-Datei die aktuelle Versionsnummer des Projekts enthalten und direkt ausgelesen werden können. Der Workflow wird dann mit `workflow_call` aus einem anderen Workflow aufgerufen und verwendet den Pfad zur `.csproj`-Datei und den Repository-Namen als Eingabeparameter.

Beim Aufrufen dieses Workflows von einem anderen Workflow aus würden Sie es so machen:

```yaml
jobs:
  call-nuget-package-creation:
    uses: ./.github/workflows/nuget-package-creation.yml@main
    with:
      csprojPath: 'Pfad/zu/Ihrem/Projekt.csproj'
      repository: 'IhrGitHubBenutzername/IhrRepository'
```

Dies würde den wiederverwendbaren Workflow aufrufen und die erforderlichen Informationen übergeben.

Bitte beachten Sie, dass Sie die GitHub Secrets (`NUGET_API_KEY`) entsprechend einrichten und ggf. den Workflow an Ihre spezifischen Anforderungen anpassen müssen.
