### ISSUE TITLE
Wiederverwendbarer Release Drafter-Workflow

### ISSUE THREAD

**Issue by kurmann** [kurmann/GitHub.Workflows#63]
- [ ] Dieser Workflow soll wiederverwendbar sein. 
- [ ] Die [Outputs des Release-Drafters](https://github.com/marketplace/actions/release-drafter#action-outputs) sollen weitergeleitet werden

```yaml

# release-management.yml
name: Release Management

on:
  push:
    branches:
      - main

jobs:
  prepare_and_draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Keine NEW_VERSION Umgebungsvariable hier setzen, da Release Drafter bereits Variablen zur Verfügung stellt.
        with:
          config-name: release-drafter-config.yml

```
